version: "3.9"
   
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile-core
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - "./data/oas:/data"
    environment:
      OAS_ADMIN_PASSWORD: "password"
      REDIS_URL: "redis://redis:6379/0"
      ELASTICSEARCH_URL: "http://elasticsearch:9200/"
      COUCHDB_URL: "http://admin:password@couchdb:5984/oas"

  worker:
    build: 
      context: .
      dockerfile: Dockerfile-worker
    volumes:
      - "./data/oas:/data"
    environment:
      OAS_URL: "http://admin:password@backend:8080/api/v1"
      REDIS_URL: "redis://redis:6379/0"

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data

  couchdb:
    image: couchdb:3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
      - COUCHDB_SECRET=secret
      - ERL_FLAGS=-setcookie "brumbrum"
    volumes:
      - ./data/couch:/opt/couchdb/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    volumes:
      - "./data/elastic:/usr/share/elasticsearch/data"
    environment:
      http.host: 0.0.0.0
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
      TAKE_FILE_OWNERSHIP: 1
